stages:
  compose:
    cmd: python src/compose.py
    deps:
    - src/compose.py
    - src/config.py
    - src/data_transformer.py
    - src/utils.py
    - src/datasets.py
    params:
      - compose
    outs:
    - data/${compose.output}
  prepare:
    cmd: python src/prepare.py
    deps:
    - data/${compose.output}
    - src/prepare.py
    - src/config.py
    - src/data_transformer.py
    - src/utils.py
    - src/datasets.py
    params:
      - prepare
    outs:
    - data/${prepare.output}
  diagrams:
    cmd: python src/diagrams.py
    deps:
    - data/${prepare.output}
    - src/diagrams.py
    - src/config.py
    - src/data_transformer.py
    - src/utils.py
    - src/datasets.py
    params:
      - diagrams
    outs:
    - data/${diagrams.output}
    # frozen: true
  featurize:
    cmd: python src/featurize.py
    deps:
      - data/${diagrams.output}
      - src/featurize.py
      - src/config.py
      - src/data_transformer.py
      - src/utils.py
      - src/datasets.py
    params:
      - featurize
    outs:
      - data/${featurize.output}
  rfe_reduce:
    cmd: python src/rfe_reduce.py
    deps:
      - data/${featurize.output}
      - src/spotcheck.py
      - src/rfe_reduce.py
      - src/config.py
      - src/data_transformer.py
      - src/utils.py
      - src/datasets.py
    outs:
      - metrics/rfe_results.pkl
