stages:
  compose:
    cmd: python src/compose.py
    deps:
    - src/compose.py
    - src/data_transformer.py
    - src/utils.py
    - src/datasets.py
    params:
      - compose
      - metadata
    outs:
    - data/${compose.output}
  prepare:
    cmd: python src/prepare.py
    deps:
    - data/${compose.output}
    - src/prepare.py
    - src/data_transformer.py
    - src/utils.py
    params:
      - prepare
      - metadata
    outs:
    - data/${prepare.output}
    frozen: true
  diagrams:
    cmd: python src/diagrams.py
    deps:
    - data/${prepare.output}
    - src/diagrams.py
    - src/data_transformer.py
    - src/utils.py
    params:
      - diagrams
      - metadata
    outs:
    - data/${diagrams.output}
  featurize:
    cmd: python src/featurize.py
    deps:
      - data/${diagrams.output}
      - src/featurize.py
      - src/feature_list.py
      - src/data_transformer.py
      - src/utils.py
    params:
      - featurize
      - metadata
    outs:
      - data/${featurize.output}
  train_test_split:
    cmd: python src/train_test_split.py
    deps:
      - data/${featurize.output}
      - src/train_test_split.py
      - src/utils.py
    params:
      - train_test_split
      - metadata
    outs:
      - data/${train_test_split.training_output}
      - data/${train_test_split.test_output}
  rfe_reduce:
    cmd: python src/rfe_reduce.py
    deps:
      - data/${train_test_split.training_output}
      - src/ml_utils.py
      - src/rfe_reduce.py
      - src/utils.py
    params:
      - rfe_reduce
      - metadata
    outs:
      - data/${rfe_reduce.output}
      - data/${rfe_reduce.rfecv_output}
    frozen: true
  crossvalidate:
    cmd: python src/crossvalidate.py
    deps:
      - data/${train_test_split.training_output}
      - data/${rfe_reduce.output}
      - src/crossvalidate.py
      - src/ml_utils.py
      - src/utils.py
    params:
      - crossvalidate
      - metadata
      - model
    metrics:
      - metrics/${crossvalidate.output}
  optuna:
    cmd: python src/optuna_optim.py
    deps:
      - data/${train_test_split.training_output}
      - data/${rfe_reduce.output}
      - src/optuna_optim.py
      - src/crossvalidate.py
      - src/ml_utils.py
      - src/utils.py
    params:
      - crossvalidate
      - metadata
      - model.name
    metrics:
      - metrics/optuna_results.json

