compose:
  dataset: lab_data
  output: data.pkl
prepare:
  output: data_prepared.pkl
  window_size: 700
  window_step: 100
  random_seed: 42
  augment_percent: 100
  augment_params:
    sigma: 5
  augmenter: None
  partial_windows: false
  subsample: false
diagrams:
  output: diagrams.pkl
  restrict: 500
  columns:
    xy:
    - acc_x
    - acc_y
    xz:
    - acc_x
    - acc_z
    yz:
    - acc_y
    - acc_z
  params:
  - dim: 2
  - dim: 3
  - dim: 4
  - dim: 10
  - dim: 2
    kind: abs
  - dim: 10
    kind: abs
  - dim: 2
    kind: phi
  - dim: 10
    kind: phi
  - dim: 2
    kind: abs
    fil: star
  - dim: 2
    kind: phi
    fil: star
  - dim: 2
    step: 30
  - dim: 4
    step: 30
featurize:
  output: features.pkl
train_test_split:
  training_output: train_features.pkl
  test_output: test_features.pkl
  test_proportion: 0.2
metadata:
  label_column: acc_gyro_event
  timestamp_column: acc_gyro_timestamp
  correct_labels:
  - 0
  - 1
  - 2
  - 4
  - 8
  timestamp_multiplier: 0.0001
  signal_columns:
    acc:
    - acc_x
    - acc_y
    - acc_z
    gyro:
    - gyro_x
    - gyro_y
    - gyro_z
  scalar_columns:
  - patient_id
  - measure_id
  - augmented
  datetime_column: packet_start_time
  patient_column: patient_id
  measure_column: measure_id
  augment_column: augmented
rfe_reduce:
  input: train_features.pkl
  output: features_rank.pkl
  rfecv_output: rfecv_results.pkl
  cycles_to_run: 1
  rfe_groups: false
  random_seed: 0
  restrict: 200
crossvalidate:
  random_seed: 42
  features: 100
  cv: 5
  output_categories: all
  use_pipeline: false
  output: crossval_results.json
model:
  name: rf
  n_estimators: 200
  criterion: gini
  max_depth: null
  max_features: sqrt
  max_leaf_nodes: null
  min_impurity_decrease: 0.0
  min_samples_leaf: 1
  min_samples_split: 2
  min_weight_fraction_leaf: 0.0
  max_samples: null
  oob_score: false
  ccp_alpha: 0.0
  class_weight: null
directories:
  data: data
  metrics: metrics
