directories:
  data: data
  metrics: metrics
defaults:
  - compose: default
  - prepare: default
  - diagrams: default
  - featurize: default
  - train_test_split: default
  - metadata: default
  - rfe_reduce: default
  - crossvalidate: default
  - model: random_forest
