directories:
  data: data
defaults:
  - compose: default
  - prepare: default
  - diagrams: default
  - featurize: default
  - train_test_split: default
  - metadata: default
  - rfe_reduce: default

